Config.WagonEquipment = {
[1] = { -- COLORS (COLOR ID, PRICE, LABEL)
["cart01"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	 {21, 1, "Red Yellow"},
	 {22, 1, "Simple Worn Cream"},
	 {23, 1, "Worn Red Cream"},
	 {24, 1, "Loco Cream Red"},
	 {25, 1, "Red Yellow"},
	 {26, 1, "Simple Worn Cream"},
	 {27, 1, "Worn Red Cream"},                
	},
["ArmySupplyWagon"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},       
	},
["bountywagon01x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
},
["buggy01"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	},
["buggy02"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	},
["buggy03"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	},
["cart02"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	 {21, 1, "Red Yellow"},
	 {22, 1, "Simple Worn Cream"},
	 {23, 1, "Worn Red Cream"},
	 {24, 1, "Loco Cream Red"},          
	},
["cart03"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	 {21, 1, "Red Yellow"},
	 {22, 1, "Simple Worn Cream"},
	 {23, 1, "Worn Red Cream"},
	 {24, 1, "Loco Cream Red"},
	 {25, 1, "Red Yellow"},   
	},
["cart04"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},            
	},
["cart05"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	 {21, 1, "Red Yellow"},
	 {22, 1, "Simple Worn Cream"},
	 {23, 1, "Worn Red Cream"},
	 {24, 1, "Loco Cream Red"},
	},
["cart06"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	 {21, 1, "Red Yellow"},
	 {22, 1, "Simple Worn Cream"},
	 {23, 1, "Worn Red Cream"},
	 {24, 1, "Loco Cream Red"},
	 {25, 1, "Red Yellow"},
	},
["cart07"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	 {21, 1, "Red Yellow"},
	 {22, 1, "Simple Worn Cream"},
	 {23, 1, "Worn Red Cream"},
	 {24, 1, "Loco Cream Red"},
	},
["cart08"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	},
["chuckwagon000X"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	},
["chuckwagon002X"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	},
["coach2"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	},
["coach3"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	},
["coach4"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	},
["coach5"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	},
["coach6"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	},
["coal_wagon"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	 {21, 1, "Red Yellow"},
	 {22, 1, "Simple Worn Cream"},
	 {23, 1, "Worn Red Cream"},
	 {24, 1, "Loco Cream Red"},
	},
["gatchuck"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	},
["gatchuck_2"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	},
["huntercart01"] = {
	 {0, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	},
["logwagon"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	},
["oilWagon01x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	},
["oilWagon02x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	},
["policeWagon01x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	},
["policeWagongatling01x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	},
["stagecoach001x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	},
["stagecoach002x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	},
["stagecoach003x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	},
["stagecoach004_2x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	},
["stagecoach004x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	},
["stagecoach005x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	},
["stagecoach006x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	},
["supplywagon"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	},
["coal_wagon"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},        
	},
["wagon02x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	 {21, 1, "Red Yellow"},
	 {22, 1, "Simple Worn Cream"},
	},
["wagon03x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	},
["wagon04x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	 {21, 1, "Red Yellow"},
	},
["wagon05x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	},
["wagon06x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	},
["wagonarmoured01x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	 {8, 1, "Loco Cream Red"},
	 {9, 1, "Red Yellow"},
	 {10, 1, "Simple Worn Cream"},
	 {11, 1, "Worn Red Cream"},                
	 {12, 1, "Simple Cream"},
	 {13, 1, "Double Yellow"},
	 {14, 1, "Loco Cream Blue"},
	 {15, 1, "Yellow Cream"},
	 {16, 1, "Simple Worn Yellow"},
	 {17, 1, "Worn Cream"},
	 {18, 1, "Simple Yellow"},
	 {19, 1, "Double Red Cream"},
	 {20, 1, "Loco Cream Red"},
	 {21, 1, "Red Yellow"},
	 {22, 1, "Simple Worn Cream"},
	 {23, 1, "Worn Red Cream"},
	 {24, 1, "Loco Cream Red"},
	 {25, 1, "Red Yellow"},
	 {26, 1, "Simple Worn Cream"},
	 {27, 1, "Worn Red Cream"},                
	 {28, 1, "Worn Red Cream"},
	 {29, 1, "Simple Worn Cream"},
	 {30, 1, "Worn Red Cream"},
	 {31, 1, "Worn Red Cream"},
	},
["wagoncircus01x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	},
["wagonCircus02x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	},
["wagonDairy01x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	},
["WAGONDOC01X"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	},
["wagonPrison01x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	 {7, 1, "Double Red Cream"},
	},
["wagontraveller01x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"}
	},
["wagonWork01x"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	},
["warWagon2"] = {
	 {00, 0, "Select Colors"},
	 {1, 1, "Double Yellow"},
	 {2, 1, "Loco Cream Blue"},
	 {3, 1, "Yellow Cream"},
	 {4, 1, "Simple Worn Yellow"},
	 {5, 1, "Worn Cream"},
	 {6, 1, "Simple Yellow"},
	},
},
--------------------------------------------------------------------------------------------------------------- 
[2]= { -- LIVERY
["cart01"] = {
     {00, 0, "Select Livery"},               
	 {1, 2, "Simple Cream"},
	 {2, 2, "Tapered Double Yellow"},
	 {3, 2, "Loco Cream Blue"},
	 {4, 2, "Flourish Yellow Cream"},
	 {5, 2, "Simple Worn Yellow"},
	 {6, 2, "Tapered Worn Cream"},
	 {7, 2, "Simple Yellow"},
	 {8, 2, "Tapered Double Red Cream"},
	 {9, 2, "Loco Cream Red"},
	 {10, 2, "Flourish Red Yellow"},
	 {11, 2, "Simple Worn Cream"},
	 {12, 2, "Tapered Worn Red Cream"},  
	},
["ArmySupplyWagon"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "US Army"},
	},
["bountywagon01x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Livery1"},
	 {2, 2, "Livery2"},
	 {3, 2, "Livery3"},
},
["buggy01"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Simple Yellow"},
	 {2, 2, "Flourish Red Yellow"},
	 {3, 2, "Ornate Red Yellow"},
	 {4, 2, "Fancy Yellow Brown"},
	 {5, 2, "Simple Red"},
	 {6, 2, "Flourish Orange Red"},
	 {7, 2, "Ornate Red Orange"},
	 {8, 2, "Fancy Red Orange"},
	 {9, 2, "Simple Cream"},
	 {10, 2, "Flourish Gold Cream"},
	 {11, 2, "Ornate Gold Black"},
	 {12, 2, "Fancy Gold"},
	 {13, 2, "Simple Black"},
	 {14, 2, "Flourish Red Black"},
	 {15, 2, "Ornate Red Black"},
	},
["buggy02"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Simple Yellow"},
	 {2, 2, "Flourish Red Yellow"},
	 {3, 2, "Ornate Red Yellow"},
	 {4, 2, "Fancy Yellow Brown"},
	 {5, 2, "Simple Red"},
	 {6, 2, "Flourish Orange Red"},
	 {7, 2, "Ornate Red Orange"},
	 {8, 2, "Fancy Red Orange"},
	 {9, 2, "Simple Cream"},
	 {10, 2, "Flourish Gold Cream"},
	 {11, 2, "Ornate Gold Black"},
	 {12, 2, "Fancy Gold"},
	 {13, 2, "Simple Black"},
	 {14, 2, "Flourish Red Black"},
	 {15, 2, "Ornate Red Black"},
	},
["buggy03"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Simple Yellow"},
	 {2, 2, "Flourish Red Yellow"},
	 {3, 2, "Ornate Red Yellow"},
	 {4, 2, "Fancy Yellow Brown"},
	 {5, 2, "Simple Red"},
	 {6, 2, "Flourish Orange Red"},
	 {7, 2, "Ornate Red Orange"},
	 {8, 2, "Fancy Red Orange"},
	 {9, 2, "Simple Cream"},
	 {10, 2, "Flourish Gold Cream"},
	 {11, 2, "Ornate Gold Black"},
	 {12, 2, "Fancy Gold"},
	 {13, 2, "Simple Black"},
	 {14, 2, "Flourish Red Black"},
	},
["cart02"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Tapered Double Red Yellow"},
	 {2, 2, "Crossed Yellow Grey"},
	 {3, 2, "Leaf Yellow"},
	 {4, 2, "Flourish Red Yellow"},
	 {5, 2, "Tapered Worn Grey Yellow"},
	 {6, 2, "Simple Worn Cream"},
	 {7, 2, "Leaf Gold"},
	 {8, 2, "Flourish Gold"},
	 {9, 2, "Tapered Double Red Grey"},
	 {10, 2, "Crossed Red Yellow"},
	 {11, 2, "Leaf Red Yellow"},
	 {12, 2, "Flourish Brown"},
	 {13, 2, "Tapered Worn Red Yellow"},
	 {14, 2, "Simple Worn Yellow"},
	 {15, 2, "Leaf Cream Red"},
	 {16, 2, "Flourish Yellow"},
	},
["cart03"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Tapered Double Red Yellow"},
	 {2, 2, "Crossed Yellow Grey"},
	 {3, 2, "Leaf Yellow"},
	 {4, 2, "Flourish Red Yellow"},
	 {5, 2, "Tapered Worn Grey Yellow"},
	 {6, 2, "Simple Worn Cream"},
	 {7, 2, "Leaf Gold"},
	 {8, 2, "Flourish Gold"},
	 {9, 2, "Tapered Double Red Grey"},
	},
["cart04"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Tapered Double Red Yellow"},
	 {2, 2, "Crossed Yellow Grey"},
	 {3, 2, "Leaf Yellow"},
	 {4, 2, "Flourish Red Yellow"},
	 {5, 2, "Tapered Worn Grey Yellow"},
	 {6, 2, "Simple Worn Cream"},
	},
["cart05"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Tapered Double Red Yellow"},
	 {2, 2, "Crossed Yellow Grey"},
	 {3, 2, "Leaf Yellow"},
	 {4, 2, "Flourish Red Yellow"},
	 {5, 2, "Tapered Worn Grey Yellow"},
	 {6, 2, "Simple Worn Cream"},
	 {7, 2, "Leaf Gold"},
	 {8, 2, "Flourish Gold"},
	 {9, 2, "Tapered Double Red Grey"},
	},
["cart06"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Tapered Double Red Yellow"},
	 {2, 2, "Crossed Yellow Grey"},
	 {3, 2, "Leaf Yellow"},
	 {4, 2, "Flourish Red Yellow"},
	 {5, 2, "Tapered Worn Grey Yellow"},
	 {6, 2, "Simple Worn Cream"},
	 {7, 2, "Leaf Gold"},
	 {8, 2, "Flourish Gold"},
	 {9, 2, "Tapered Double Red Grey"},
	 {10, 2, "Crossed Red Yellow"},
	 {11, 2, "Leaf Red Yellow"},
	 {12, 2, "Flourish Brown"},
	},
["cart07"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Tapered Double Red Yellow"},
	 {2, 2, "Crossed Yellow Grey"},
	 {3, 2, "Leaf Yellow"},
	 {4, 2, "Flourish Red Yellow"},
	 {5, 2, "Tapered Worn Grey Yellow"},
	 {6, 2, "Simple Worn Cream"},
	 {7, 2, "Leaf Gold"},
	 {8, 2, "Flourish Gold"},
	 {9, 2, "Tapered Double Red Grey"},
	 {10, 2, "Crossed Red Yellow"},
	 {11, 2, "Leaf Red Yellow"},
	},
["cart08"] = {
	 {00, 0, "Select Livery"},
	 {1, 1, "Tapered Double Red Yellow"},
	 {2, 2, "Crossed Yellow Grey"},
	 {3, 2, "Leaf Yellow"},
	 {4, 2, "Flourish Red Yellow"},
	 {5, 2, "Tapered Worn Grey Yellow"},
	 {6, 2, "Simple Worn Cream"},
	 {7, 2, "Leaf Gold"},
	 {8, 2, "Flourish Gold"},
	 {9, 2, "Tapered Double Red Grey"},
	 {10, 2, "Crossed Red Yellow"},
	 {11, 2, "Leaf Red Yellow"},
	 {12, 2, "Flourish Brown"},
	 {13, 2, "Tapered Worn Red Yellow"},
	 {14, 2, "Simple Worn Yellow"},
	 {15, 2, "Leaf Cream Red"},
	},
["chuckwagon000X"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Simple Lining Red"},
	 {2, 2, "Dot Lining Red Yellow"},
	 {3, 2, "Double Lining White Blue"},
	 {4, 2, "Flourish Yellow"},
	 {5, 2, "Simple Lining Yellow"},
	 {6, 2, "Dot Lining Orange Yellow"},
	 {7, 2, "Double Lining Black Red"},
	 {8, 2, "Flourish Red Yellow"},
	 {9, 2, "Flourish Cream Gold"},
	 {10, 2, "Flourish Red Black"},
	 {11, 2, "Double Lining Red Yellow"},
	},
["chuckwagon002X"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Simple Lining Red"},
	 {2, 2, "Dot Lining Red Yellow"},
	 {3, 2, "Double Lining White Blue"},
	 {4, 2, "Flourish Yellow"},
	 {5, 2, "Simple Lining Yellow"},
	 {6, 2, "Dot Lining Orange Yellow"},
	 {7, 2, "Double Lining Black Red"},
	 {8, 2, "Flourish Red Yellow"},
	 {9, 2, "Flourish Cream Gold"},
	 {10, 2, "Flourish Red Black"},
	 {11, 2, "Double Lining Red Yellow"},
	},
["coach2"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Davis"},
	 {2, 2, "Boles"},
	 {3, 2, "Heartlands"},
	 {4, 2, "Tapered"},
	},
["coach3"] = {
	 {00, 0, "Select Livery"},
	 {0, 2, "Lines Gold"},
	 {1, 2, "Flourish Yellow"},
	 {2, 2, "Tapered Yellow"},
	 {3, 2, "Leaf Yellow Red"},
	 {4, 2, "Lines Blue"},
	 {5, 2, "Flourish Gold Red"},
	 {6, 2, "Tapered Blue Grey"},
	 {7, 2, "Leaf Gold"},
	 {8, 2, "Lines Orange"},
	 {9, 2, "Flourish Red Cream"},
	 {10, 2, "Tapered Orange Yellow"},
	 {11, 2, "Leaf Worn"},
	 {12, 2, "Tapered Red Orange"},
	},
["coach4"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Lines Red Grey"},
	 {2, 2, "Crosshatch Red Green"},
	 {3, 2, "Accented Red Yellow"},
	 {4, 2, "Leaf Yellow"},
	 {5, 2, "Lines Red Green"},
	 {6, 2, "Crosshatch Red Yellow"},
	 {7, 2, "Accented Gold Red"},
	 {8, 2, "Leaf Red Yellow"},
	 {9, 2, "Lines Yellow Orange"},
	 {10, 2, "Crosshatch Cream"},
	 {11, 2, "Crosshatch Green"},
	 {12, 2, "Leaf Gold"},
	 {13, 2, "Lines Gold Yellow"},
	 {14, 2, "Crosshatch Gold"},
	},
["coach5"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Lines Red Grey"},
	 {2, 2, "Crosshatch Red Green"},
	 {3, 2, "Accented Red Yellow"},
	 {4, 2, "Leaf Yellow"},
	 {5, 2, "Lines Red Green"},
	 {6, 2, "Crosshatch Red Yellow"},
	 {7, 2, "Accented Gold Red"},
	 {8, 2, "Leaf Red Yellow"},
	 {9, 2, "Lines Yellow Orange"},
	 {10, 2, "Crosshatch Cream"},
	 {11, 2, "Crosshatch Green"},
	 {12, 2, "Leaf Gold"},
	},
["coach6"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Simple Cream"},
	 {2, 2, "Tapered Cream"},
	 {3, 2, "Squared Cream"},
	 {4, 2, "Leaf Cream Yellow"},
	 {5, 2, "Simple Yellow"},
	 {6, 2, "Tapered Yellow Red"},
	 {7, 2, "Squared Yellow"},
	 {8, 2, "Leaf Red Yellow"},
	 {9, 2, "Simple Red Yellow"},
	 {10, 2, "Tapered Red Yellow"},
	 {11, 2, "Squared Red"},
	 {12, 2, "Leaf Black Yellow"},
	 {13, 2, "Simple Black"},
	 {14, 2, "Tapered Gold Black"},
	 {15, 2, "Squared"},
	 {16, 2, "Leaf Gold"},
	},
["coal_wagon"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "M.Harris01"},
	 {2, 2, "Jameson01"},
	 {3, 2, "M.Harris02"},
	 {4, 2, "Jameson02"},
	},
["gatchuck"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Simple Red Yellow"},
	 {2, 2, "Tapered Yellow Cream"},
	 {3, 2, "Squared Gold Black"},
	 {4, 2, "Flourish Gold Cream"},
	 {5, 2, "Simple Cream"},
	 {6, 2, "Tapered Gold Red"},
	 {7, 2, "Squared Cream Red"},
	 {8, 2, "Flourish Black Yellow"},
	 {9, 2, "Simple Yellow Red"},
	 {10, 2, "Tapered Gold Black"},
	 {11, 2, "Squared Black Red"},
	 {12, 2, "Flourish Cream Gold"},
	 {13, 2, "Gold Cream"},
	 {14, 2, "Tapered Blue Black"},
	 {15, 2, "Squared Gold Black"},
	 {16, 2, "Flourish Yellow Red"},
	},
["gatchuck_2"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Simple Red Yellow"},
	 {2, 2, "Tapered Yellow Cream"},
	 {3, 2, "Squared Gold Black"},
	 {4, 2, "Flourish Gold Cream"},
	 {5, 2, "Simple Cream"},
	 {6, 2, "Tapered Gold Red"},
	 {7, 2, "Squared Cream Red"},
	 {8, 2, "Flourish Black Yellow"},
	 {9, 2, "Simple Yellow Red"},
	 {10, 2, "Tapered Gold Black"},
	 {11, 2, "Squared Black Red"},
	 {12, 2, "Flourish Cream Gold"},
	 {13, 2, "Gold Cream"},
	 {14, 2, "Tapered Blue Black"},
	 {15, 2, "Squared Gold Black"},
	 {16, 2, "Flourish Yellow Red"},
	},
["huntercart01"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Hunt0"},
	 {2, 2, "Hunt1"},
	 {3, 2, "Hunt2"},
	 {4, 2, "Hunt3"},
	 {5, 2, "Hunt4"},
	 {6, 2, "Hunt5"},
	},
["logwagon"] = {
	 {00, 0, "Select Livery"},
	},
["oilWagon01x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Cornwall Red Cream"},
	 {2, 2, "Cornwall Red Black"},
	 {3, 2, "Cornwall Cream Yellow"},
	 {4, 2, "Cornwall Cream Red Yellow"},
	 {5, 2, "Cornwall White Orange"},
	 {6, 2,  "Cornwall Yellow Red"},
	},
["oilWagon02x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Cornwall Red Cream"},
	 {2, 2, "Cornwall Red Black"},
	 {3, 2, "Cornwall Cream Yellow"},
	 {4, 2, "Cornwall Cream Red Yellow"},
	 {5, 2, "Cornwall White Orange"},
	 {6, 2,  "Cornwall Yellow Red"},
	},
["policeWagon01x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Police Red White"},
	},
["policeWagongatling01x"] = {
	 {00, 0, "Select Colors"},
	 {1, 2, "Police Red White"},
	},
["stagecoach001x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Davis"},
	 {2, 2, "Boles"},
	 {3, 2, "Heartlands"},
	 {4, 2, "Ornate"},
	},
["stagecoach002x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Davis"},
	 {2, 2, "Boles"},
	 {3, 2, "Heartlands"},
	 {4, 2, "Tapered"},
	},
["stagecoach003x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Davis"},
	 {2, 2, "Boles"},
	 {3, 2, "Heartlands"},
	 {4, 2, "Ornate"},
	},
["stagecoach004_2x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Davis"},
	 {2, 2, "Boles"},
	 {3, 2, "Heartland"},
	 {4, 2, "Tapered"},
	 {5, 2, "Lemoyne"},
	},
["stagecoach004x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Davis"},
	},
["stagecoach005x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Davis"},
	 {2, 2, "Boles"},
	 {3, 2, "Heartland"},
	 {4, 2, "Tapered"},
	},
["stagecoach006x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Davis"},
	 {2, 2, "Boles"},
	 {3, 2, "Heartland"},
	 {4, 2, "Tapered"},
	},
["supplywagon"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "US Army"},
	},
["coal_wagon"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "M.Harris01"},
	 {2, 2, "Jameson01"},
	 {3, 2, "M.Harris02"},
	 {4, 2, "Jameson02"},
	},
["wagon02x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Simple Red"},
	 {2, 2, "Double Cream Yellow"},
	 {3, 2, "Tapered Red"},
	 {4, 2, "Flourish Red Cream"},
	 {5, 2, "Jameson"},
	 {6, 2, "Cornwall"},
	 {7, 2, "Simple Orange"},
	 {8, 2, "Double Lining"},
	 {9, 2, "Tapered Orange"},
	 {10, 2, "Flourish Red Yellow"},
	 {11, 2, "Simple Black"},
	 {12, 2, "Double Cream Yellow"},
	 {13, 2, "Tapered Cream Yellow"},
	 {14, 2, "Flourish Gold"},
	 {15, 2, "Simple Yellow"},
	 {16, 2, "Double Red Yellow"},
	 {17, 2, "Tapered Gold"},
	},
["wagon03x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Simple Brown Red"},
	 {2, 2, "Double Red Yellow"},
	 {3, 2, "Tapered Yellow Red"},
	 {4, 2, "Flourish Gold Black"},
	 {5, 2, "Simple Red"},
	 {6, 2, "Double Yellow Red"},
	 {7, 2, "Tapered Cream Red"},
	 {8, 2, "Flourish Red Black"},
	 {9, 2, "Simple Black"},
	 {10, 2, "Double Lining"},
	 {11, 2, "Tapered Yellow"},
	 {12, 2, "Flourish Red Gold"},
	 {13, 2, "Simple Brown"},
	 {14, 2, "Double Red"},
	 {15, 2, "Tapered Cream Red"},
	 {16, 2, "Flourish Red Yellow"},
	},
["wagon04x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Simple Cream"},
	 {2, 2, "Double Yellows"},
	 {3, 2, "Tapered Red"},
	 {4, 2, "Flourish Red Yellow"},
	 {5, 2, "Simple Red"},
	 {6, 2, "Double Yellow White"},
	 {7, 2, "Tapered Yellow"},
	 {8, 2, "Flourish Cream Black"},
	 {9, 2, "Simple Green"},
	 {10, 2, "Double Red Yellow"},
	 {11, 2, "Tapered Cream"},
	 {12, 2, "Flourish Black Gold"},
	 {13, 2, "Simple Black Cream"},
	 {14, 2, "Double Brown Orange"},
	 {15, 2, "Tapered Orange"},
	 {16, 2, "Flourish Cream Red"},
	},
["wagon05x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Simple Yellow"},
	 {2, 2, "Tapered Gold"},
	 {3, 2, "Double Cream Orange"},
	 {4, 2, "Flourish Yellow Orange"},
	 {5, 2, "Simple Cream"},
	 {6, 2, "Tapered Orange"},
	 {7, 2, "Double Cream Red"},
	 {8, 2, "Flourish Yellow Red"},
	 {9, 2, "Simple Red"},
	 {10, 2, "Tapered Yellow"},
	 {11, 2, "Double Creams"},
	 {12, 2, "Flourish Black Gold"},
	 {13, 2, "Simple Red"},
	 {14, 2, "Tapered Green"},
	 {15, 2, "Double Yellow Cream"},
	 {16, 2, "Flourish Yellow Cream"},
	 {17, 2, "Simple Orange"},
	 {18, 2, "Tapered Black"},
	 {19, 2, "Double Black Red"},
	 {20, 2, "Flourish Worn Red Cream"},
	},
["wagon06x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Simple Cream Red"},
	 {2, 2, "Double Red Yellow"},
	 {3, 2, "Flourish Cream Gold"},
	 {4, 2, "Flourish II Red Black Yellow"},
	 {5, 2, "Simple Red"},
	 {6, 2, "Double Cream Yellow"},
	 {7, 2, "Flourish Black Yellow"},
	 {8, 2, "Flourish II Black Cream Gold"},
	 {9, 2, "Simple Red"},
	 {10, 2, "Double Red Cream"},
	 {11, 2, "Flourish Black Gold"},
	 {12, 2, "Flourish II Cream Orange Yellow"},
	 {13, 2, "Simple Yellow Red"},
	 {14, 2, "Double Black Red"},
	 {15, 2, "Flourish Red Yellow"},
	 {16, 2, "Flourish II Green Gold"},
	},
["wagonarmoured01x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Liv 1"},
	 {2, 2, "Liv 1a"},
	 {3, 2, "Liv 1b"},
	 {4, 2, "Liv 2"},
	 {5, 2, "Liv 2a"},
	 {6, 2, "Liv 2b"},
	 {7, 2, "Liv 3"},
	 {8, 2, "Liv 3a"},
	 {9, 2, "Liv 3b"},
	 {10, 2, "Liv 4"},
	 {11, 2, "Liv 4a"},
	 {12, 2, "Liv 4b"},
	 {13, 2, "Liv 5"},
	 {14, 2, "Liv 5a"},
	 {15, 2, "Liv 5b"},
	 {16, 2, "Liv 6"},
	 {17, 2, "Liv 6a"},
	 {18, 2, "Liv 6b"},
	 {19, 2, "Liv 7"},
	 {20, 2, "Liv 7a"},
	 {21, 2, "Liv 7b"},
	 {22, 2, "Liv 8"},
	 {23, 2, "Liv 8a"},
	 {24, 2, "Liv 8b"},
	 {25, 2, "Liv 9"},
	 {26, 2, "Liv 9a"},
	 {27, 2, "Liv 9b"},
	 {28, 2, "Liv 10"},
	 {29, 2, "Liv 10a"},
	 {30, 2, "Liv 10b"},
	 {31, 2, "Liv 10c"},
	},
["wagoncircus01x"] = {
	 {00, 0, "Select Livery"},
	},
["wagonCircus02x"] = {
	 {00, 0, "Select Livery"},
	},
["wagonDairy01x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Kauffman"},
	 {2, 2, "Kauffman Worn"},
	},
["WAGONDOC01X"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Doctors"},
	},
["wagonPrison01x"] = {
	 {00, 0, "Select Livery"},
	},
["wagontraveller01x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Traveller Red Yellow"},
	},
["wagonWork01x"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Wakefield"},
	},
["warWagon2"] = {
	 {00, 0, "Select Livery"},
	 {1, 2, "Simple Lining"},
	 {2, 2, "Double Lining"},
	 {3, 2, "Tapered"},
	 {4, 2, "Gold Leaf"},
	},
},
            
-------------------------------------------------------------------------------------------------------------------------
            
[3]= { -- PROPS
["cart01"] = {
 	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},                  
 	 {"pg_re_checkpoint02x_food", 5, "Food"},
	 {"pg_re_moonshineCampgroupCart01x", 5, "Moonshine"},
	 {"pg_teamster_cart01_breakables", 5, "Break Team 1"},
	 {"pg_teamster_cart01_gen", 5, "Break Team 2"},
	 {"pg_veh_cart01_1", 5, "Cart 1"},
	 {"pg_veh_cart01_2", 5, "Cart 2"},
	 {"pg_veh_cart01_3", 5, "Cart 3"},                 
    },
["coach3"] = {
    {00, 0, "No Props"}
	},
["ArmySupplyWagon"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},                  
 	 {"pg_rc_monroe1_01x", 5, "Monroe"},
	},
["bountywagon01x"] = {
	 {00, 0, "No Props"}
},
["buggy01"] = {
	 {00, 0, "No Props"}
	},
["buggy02"] = {
	 {00, 0, "No Props"}
	},
["buggy03"] = {
	 {00, 0, "No Props"}
	},
["cart02"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},                  
 	 {"pg_mission_caravanCart02x", 5, "Caravan"},
	 {"pg_teamster_cart02_breakables", 5, "Team Break"},
     {"pg_teamster_cart02_gen", 5, "Team Gen"},           
	},
["cart03"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},                  
 	 {"pg_delivery_Coal02x", 5, "Delivery Coal"},
	 {"pg_mp_moonshinebiz_supplies01x_cart03", 5, "Moonshine"},
     {"pg_teamster_cart03_breakables", 5, "Team Break"},           
     {"pg_teamster_cart03_gen", 5, "Team Gen"},   
     {"pg_veh_cart03_1", 5, "Veh Cart 1"},   
     {"pg_veh_cart03_2", 5, "Veh Cart 2"},   
     {"pg_veh_cart03_barrels01x", 5, "Barrels"},               
	},
["cart04"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
 	 {"pg_mission_caravanCart04x", 5, "Mission Caravan"},
     {"pg_teamster_cart04_breakables", 5, "Team Break"},
     {"pg_teamster_cart04_gen", 5, "Team Gen"},
     {"pg_veh_cart04_1", 5, "Veh Cart 1"},
     {"pg_veh_cart04_2", 5, "Veh Cart 2"},
	},
["cart05"] = {
	 {00, 0, "No Props"}
	},
["cart06"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_teamster_cart06_breakables", 5, "Team Break"},
     {"pg_teamster_cart06_gen", 5, "Team Gen"},
     {"pg_veh_cart06_1", 5, "Veh Cart 1"},
     {"pg_veh_cart06_2", 5, "Veh Cart 2"},
	},
["cart07"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_teamster_cart07_breakables", 5, "Team Break"},
     {"pg_teamster_cart07_gen", 5, "Team Gen"},
     {"pg_veh_cart07_1", 5, "Veh Cart 1"},
     {"pg_veh_cart07_2", 5, "Veh Cart 2"},
	},
["cart08"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_teamster_cart08_breakables", 5, "Team Break"},
     {"pg_teamster_cart08_gen", 5, "Team Gen"},
     {"pg_veh_cart08_1", 5, "Veh Cart 1"},
     {"pg_veh_cart08_2", 5, "Veh Cart 2"},
	},
["chuckwagon000X"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_re_fleeingfamily01x", 5, "Fleeing Family"},
     {"pg_teamster_chuckwagon000x_breakables", 5, "Team Break"},
 	 {"pg_teamster_chuckwagon000x_gen", 5, "Team Gen"},
     {"pg_veh_chuckwagon000x_1", 5, "Chuck 1"},
	 {"pg_veh_chuckwagon000x_2", 5, "Chuck 2"},
     {"pg_veh_chuckwagon000x_3", 5, "Chuck 3"},
 	 {"pg_veh_chuckwagon000x_2a", 5, "Chuck 4"},
     {"pg_veh_chuckwagon000x_3a", 5, "Chuck 5"},
     {"pg_veh_chuckwagon000x_4", 5, "Chuck 6"},
	 {"pg_veh_chuckwagon000x_orange_1", 5, "Chuck Orange"},
     {"pg_vehload_cotton01", 5, "Cotton"},
 	 {"pg_vehload_crates01", 5, "Crates"},
     {"pg_vehload_haybale01", 5, "Haybales"},
     {"pg_vehload_livestock01", 5, "Livestock"},
	 {"pg_vehload_lumber01", 5, "Lumber"},
     {"pg_vehload_sacks01", 5, "Sacks"},
 	 {"pg_vl_blacksmith01", 5, "Blacksmith"},
     {"pg_vl_butcher01", 5, "Butcher"},
     {"pg_vl_craftsman01", 5, "Craftsman"},
	 {"pg_vl_delivery01", 5, "Delivery"},
     {"pg_vl_farmer01", 5, "Farmer 1"},
 	 {"pg_vl_farmer02", 5, "Farmer 2"},
     {"pg_vl_ferrier01", 5, "Ferrier"},
     {"pg_vl_fisherman01", 5, "Fisherman"},
     {"pg_vl_hunter01", 5, "Hunter"},
     {"pg_vl_movingFamily01", 5, "Movin Family"},
 	 {"pg_vl_rancher01", 5, "Rancher 1"},
     {"pg_vl_rancher02", 5, "Rancher 2"},
     {"pg_vl_rancher03", 5, "Rancher 3"},
	 {"pg_vl_rancher04", 5, "Rancher 4"},
 	 {"pg_vl_rancher05", 5, "Rancher 5"},
     {"pg_vl_tradesman01", 5, "Tradesman 1"},
     {"pg_vl_tradesman02", 5, "Tradesman 2"},
     {"pg_vl_tradesman03", 5, "Tradesman 3"},
     {"pg_vl_tradesman04", 5, "Tradesman 4"},
 	 {"pg_vl_travellingFamily01", 5, "Travelling Family"},
     {"pg_vl_travellingLabour01", 5, "Travelling Labour"},
	},
["chuckwagon002X"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_rc_exconfederates1_01x", 5, "Federates"},
     {"pg_teamster_chuckwagon002x_breakables", 5, "Team Break"},
 	 {"pg_teamster_chuckwagon002x_gen", 5, "Team Gen"},
     {"pg_veh_chuckwagon002x_1", 5, "Chuck 1"},
	 {"pg_veh_chuckwagon002x_2", 5, "Chuck 2"},
     {"pg_veh_chuckwagon002x_3", 5, "Chuck 3"},
 	 {"pg_vl_blacksmith01", 5, "Blacksmith"},
     {"pg_vl_butcher01", 5, "Butcher"},
     {"pg_vl_craftsman01", 5, "Craftsman"},
	 {"pg_vl_delivery01", 5, "Delivery"},
     {"pg_vl_farmer01", 5, "Farmer 1"},
 	 {"pg_vl_farmer02", 5, "Farmer 2"},
     {"pg_vl_ferrier01", 5, "Ferrier"},
     {"pg_vl_fisherman01", 5, "Fisherman"},
	 {"pg_vl_hunter01", 5, "Hunter"},
     {"pg_vl_movingFamily01", 5, "Moving Family"},
 	 {"pg_vl_rancher01", 5, "Rancher 1"},
     {"pg_vl_rancher02", 5, "Rancher 2"},
     {"pg_vl_rancher03", 5, "Rancher 3"},
	 {"pg_vl_rancher04", 5, "Rancher 4"},
     {"pg_vl_rancher05", 5, "Rancher 5"},
 	 {"pg_vl_tradesman01", 5, "Tradesman 1"},
     {"pg_vl_tradesman02", 5, "Tradesman 2"},
     {"pg_vl_tradesman03", 5, "Tradesman 3"},
     {"pg_vl_tradesman04", 5, "Tradesman 4"},
     {"pg_vl_travellingFamily01", 5, "Travelling Family"},
 	 {"pg_vl_travellingLabour01", 5, "Travelling Labour"},
	},
["coach2"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_mission_mary3_01x", 5, "Mary"},
     {"pg_re_coachrobbery01x", 5, "Robbery"},
 	 {"pg_veh_coach2_1", 5, "Coach 1"},
     {"pg_veh_coach2_bootA", 5, "Coach 2"},
	},
["coach4"] = {
	 {00, 0, "No Props"}
	},
["coach5"] = {
	 {00, 0, "No Props"}
	},
["coach6"] = {
	 {00, 0, "No Props"}
	},
["coal_wagon"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_delivery_Coal01x", 5, "Coal"},
	},
["gatchuck"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_mission_native2_01x", 5, "Native"},
     {"pg_teamster_payroll01x_gat", 5, "Team Payroll"},
	},
["gatchuck_2"] = {
	 {00, 0, "No Props"}
	},
["huntercart01"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_mp005_huntingWagonTarp01", 5, "Wagon Tarp"},
	},
["logwagon"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_veh_logwagon_1", 5, "Log Wagon"},
	},
["oilWagon01x"] = {
	 {00, 0, "No Props"}
	},
["oilWagon02x"] = {
	 {00, 0, "No Props"}
	},
["policeWagon01x"] = {
	 {00, 0, "No Props"}
	},
["policeWagongatling01x"] = {
	 {00, 0, "No Props"}
	},
["stagecoach001x"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_veh_stagecoach001x_1", 5, "Stage 1"},
     {"pg_veh_stagecoach001x_2", 5, "Stage 2"},         
	},
["stagecoach002x"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_veh_stagecoach002x_1", 5, "Stage 1"},
     {"pg_veh_stagecoach002x_2", 5, "Stage 2"},
     {"pg_veh_stagecoach002x_bootA", 5, "Stage Boot"},                    
	},
["stagecoach003x"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_veh_stagecoach003x_bootA", 5, "Stage Boot"},
	},
["stagecoach004_2x"] = {
	 {00, 0, "No Props"}
	},
["stagecoach004x"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_mission_utp2_coachLockbox", 5, "Coach Lock"},
     {"pg_teamster_armourwag_breakables", 5, "Team Break"},
     {"pg_teamster_armourwag_gen", 5, "Team Gen"},
	},
["stagecoach005x"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_veh_stagecoach005x_1", 5, "Stage 1"},
     {"pg_veh_stagecoach005x_2", 5, "Stage 2"},
	},
["stagecoach006x"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_veh_stagecoach006x_1", 5, "Stage 1"},
     {"pg_veh_stagecoach006x_2", 5, "Stage 2"},
	},
["supplywagon"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_mission_cornwall1_01x", 5, "Cornwall"},
     {"pg_mp_moonshinebiz_supplies02x_supwag", 5, "Moonshine"},
	 {"pg_teamster_supplywagon_breakables", 5, "Team Break"},
     {"pg_teamster_supplywagon_gen", 5, "Team Gen"},
     {"pg_delivery_Cotton01x", 5, "Cotton"},           
	},
["coal_wagon"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_delivery_Coal01x", 5, "Delivery Coal"},
	},
["wagon02x"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_gunforhire01x", 5, "Gun Hire"},
     {"pg_vehload_cotton01", 5, "Load Cotton"},
 	 {"pg_gunforhire02x", 5, "Gun Hire 2"},
     {"pg_gunforhire03x", 5, "Gun Hire 3"},
     {"Pg_Mis_Mud1_Wagon02x", 5, "Mud Wagon"},
	 {"Pg_Mis_Mud1_Wagon02x_NoLooseProps", 5, "Mud Wagon 2"},
     {"pg_mission_marston7_lumber01x", 5, "Marston Lumber"},
 	 {"pg_mission_marston7_lumber02x", 5, "Masrston Lumber 2"},
     {"pg_mission_marston7_lumber03x_doneloading", 5, "Marston Lumber 3"},
     {"pg_mission_mud1_wagon03x", 5, "Mud Wagon 2"},
     {"pg_mission_trainrob3_start01x", 5, "Train Rob"},
 	 {"pg_mission_weaponsDeal", 5, "Weapon Deal"},
     {"pg_mission_winter1_4thwagon01x", 5, "Winter Wagon"},
     {"pg_rc_BeauAndPene101x", 5, "Beau Pene"},
	 {"pg_rc_beauandpene201x", 5, "Beau Pene 2"},
     {"pg_rc_forgiven601x", 5, "Forgiven"},
 	 {"pg_rc_nativewagoncornwall01x", 5, "Native Cornwall"},
     {"pg_rc_saddiesupplies00x", 5, "Saddies Supplies"},
     {"pg_rc_saddiesupplies01x", 5, "Saddies Supplies"},
	 {"pg_re_armsdeal01x", 5, "Armsdeal"},
     {"pg_re_odriscollwagon01x", 5, "Odriscoll"},
 	 {"pg_re_supplydelivery_gsmith01x", 5, "Supply Gunsmith"},
     {"pg_re_supplyDelivery01x", 5, "Supply Delivery"},
     {"pg_re_trainholdup01x", 5, "Train Holdup"},
     {"pg_sp_MarstonsWagon02x", 5, "Marston Wagon"},
     {"pg_teamster_wagon02x_breakables", 5, "Team Break"},
 	 {"pg_teamster_wagon02x_gen", 5, "Team Gen"},
	 {"pg_teamster_wagon02x_gen02", 5, "Team Gen 2"},
 	 {"pg_wagon02xClimbtest01x", 5, "Climbtest"},
     {"pg_veh_wagon02x_1", 5, "Wagon 1"},
     {"pg_veh_wagon02x_2", 5, "Wagon 2"},
	 {"pg_veh_wagon02x_3", 5, "Wagon 3"},
     {"pg_vl_blacksmith01", 5, "Blacksmith"},
     {"pg_vl_butcher01", 5, "Butcher"},
     {"pg_vl_craftsman01", 5, "Craftsman"},
	 {"pg_vl_delivery01", 5, "Delivery"},
     {"pg_vl_farmer01", 5, "Farmer 1"},
 	 {"pg_vl_farmer02", 5, "Farmer 2"},
     {"pg_vl_ferrier01", 5, "Ferrier"},
     {"pg_vl_fisherman01", 5, "Fisherman"},
	 {"pg_vl_hunter01", 5, "Hunter"},
     {"pg_vl_movingFamily01", 5, "Moving Family"},
 	 {"pg_vl_rancher01", 5, "Rancher 1"},
     {"pg_vl_rancher02", 5, "Rancher 2"},
     {"pg_vl_rancher03", 5, "Rancher 3"},
	 {"pg_vl_rancher04", 5, "Rancher 4"},
     {"pg_vl_rancher05", 5, "Rancher 5"},
 	 {"pg_vl_tradesman01", 5, "Tradesman 1"},
     {"pg_vl_tradesman02", 5, "Tradesman 2"},
     {"pg_vl_tradesman03", 5, "Tradesman 3"},
     {"pg_vl_tradesman04", 5, "Tradesman 4"},
     {"pg_vl_travellingFamily01", 5, "Travelling Family"},
 	 {"pg_vl_travellingLabour01", 5, "Travelling Labour"},
	},
["wagon03x"] = {
	 {00, 0, "No Props"}
	},
["wagon04x"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_gunforhire01x", 5, "Gun Hire"},
     {"pg_gunforhire02x", 5, "Gun Hire 2"},
     {"pg_gunforhire03x", 5, "Gun Hire 3"},
     {"pg_mission_caravanWagon04x", 5, "Caravan"},
     {"pg_mission_mud1_jackwagon01x", 5, "Jack Wagon"},
     {"pg_mission_mud1_wagon01x", 5, "Mud Wagon 1"},
     {"pg_mission_mud1_wagon02x", 5, "Mud Wagon 2"},
     {"pg_mission_winter1_keiranWag01x", 5, "Keiran Wagon"},
     {"pg_mission_winter1_wag04_01x", 5, "Winter Wagon"},
     {"pg_teamster_wagon04x_breakables", 5, "Team Break"},
     {"pg_teamster_wagon04x_gen", 5, "Team Gen 1"},
     {"pg_teamster_wagon04x_gen02", 5, "Team Gen 2"},
     {"pg_veh_wagon04x_1", 5, "Wagon 1"},
     {"pg_veh_wagon04x_2", 5, "Wagon 2"},
     {"pg_veh_wagon04x_3", 5, "Wagon 3"},
     {"pg_vl_blacksmith01", 5, "Blacksmith"}, 
     {"pg_vl_butcher01", 5, "Butcher"},
     {"pg_vl_craftsman01", 5, "Craftsman"},
     {"pg_vl_delivery01", 5, "Delivery"},
     {"pg_vl_farmer01", 5, "Farmer 1"},
     {"pg_vl_farmer02", 5, "Farmer 2"},
     {"pg_vl_ferrier01", 5, "Ferrier"},
     {"pg_vl_fisherman01", 5, "Fisherman"},
     {"pg_vl_hunter01", 5, "Hunter"},
     {"pg_vl_movingFamily01", 5, "Moving Family"},
     {"pg_vl_rancher01", 5, "Rancher 1"},
     {"pg_vl_rancher02", 5, "Rancher 2"},
     {"pg_vl_rancher03", 5, "Rancher 3"},
     {"pg_vl_rancher04", 5, "Rancher 4"},
     {"pg_vl_rancher05", 5, "Rancher 5"},
     {"pg_vl_tradesman01", 5, "Tradesman 1"},
     {"pg_vl_tradesman02", 5, "Tradesman 2"},
     {"pg_vl_tradesman03", 5, "Tradesman 3"},
     {"pg_vl_tradesman04", 5, "Tradesman 4"},
     {"pg_vl_travellingFamily01", 5, "Travelling Family"},
     {"pg_vl_travellingLabour01", 5, "Travelling Labour"},
     {"pg_veh_germFam_wagon04x_01", 5, "Germ Family"},                     
	},
["wagon05x"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_delivery_CKToil01x", 5, "Delivery Toil"},
     {"pg_delivery_Orange01x", 5, "Delivery Orange"},
     {"pg_gunforhire01x", 5, "Gun Hire 1"},
     {"pg_gunforhire02x", 5, "Gun Hire 2"},
     {"pg_gunforhire03x", 5, "Gun Hire 3"},
     {"pg_ls_soldier2_01x", 5, "Soldier"},
     {"pg_mission_bra1_wagon", 5, "Mission Wagon"},
     {"pg_mission_brt1_jump01x", 5, "Mission Jump"},
     {"pg_mission_brt1_tomansion01x", 5, "Mission Tomansion"},
     {"pg_mission_brt2", 5, "Mission 2"},
     {"pg_mission_BRT2_escape01x", 5, "Mission Escape"},
     {"pg_mission_brt3", 5, "Mission 3"},
     {"pg_mission_caravanWagon05x", 5, "Caravan"},
     {"pg_mission_moonshineSupplies", 5, "Moonshine"},
     {"pg_rc_ridethelightning01x", 5, "Ride the Lighting"},
     {"pg_re_checkpoint01x", 5, "Checkpoint"},
     {"pg_re_savagewagon01x", 5, "Savage Wagon"}, 
     {"pg_teamster_wagon05x_breakables", 5, "Team Break"},
     {"pg_teamster_wagon05x_gen", 5, "Team Gen"},
     {"pg_veh_wagon05x_1", 5, "Wagon 1"},
     {"pg_veh_wagon05x_2", 5, "Wagon 2"},
     {"pg_veh_wagon05x_3", 5, "Wagon 3"},
     {"pg_veh_wagon05x_4", 5, "Wagon 4"},
     {"pg_veh_wagon05x_5", 5, "Wagon 5"},
     {"pg_veh_wagon05x_cotton", 5, "Wagon Cotton"},
	},
["wagon06x"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_teamster_wagon06x_breakables", 5, "Team Break"},
     {"pg_teamster_wagon06x_gen", 5, "Team Gen"},
     {"pg_veh_wagon06x_1", 5, "Wagon 1"},
     {"pg_veh_wagon06x_2", 5, "Wagon 2"},
     {"pg_veh_wagon06x_3", 5, "Wagon 3"},
	},
["wagonarmoured01x"] = {
	 {00, 0, "No Props"}
	},
["wagoncircus01x"] = {
	 {00, 0, "No Props"}
	},
["wagonCircus02x"] = {
	 {00, 0, "No Props"}
	},
["wagonDairy01x"] = {
	 {00, 0, "Select Props"},
 	 {false, 0, "Remove Prop"},
     {"pg_delivery_dairy01x", 5, "Delivery Dairy"},
	},
["WAGONDOC01X"] = {
	 {00, 0, "No Props"}
	},
["wagonPrison01x"] = {
	 {00, 0, "No Props"}
	},
["wagontraveller01x"] = {
	 {00, 0, "No Props"}
	},
["wagonWork01x"] = {
	 {00, 0, "No Props"}
	},
["warWagon2"] = {
	 {00, 0, "No Props"}
	},
},

---------------------------------------------------------------------------------------------------------------
        
[4]= { -- LIGHTS
["cart01"] = {
     {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},            
 	 {"pg_teamster_cart01_lightupgrade1", 3, "Lights 1"},
	 {"pg_teamster_cart01_lightupgrade2", 3, "Lights 2"},
	 {"pg_teamster_cart01_lightupgrade3", 3, "Lights 3"},
	 {"pg_veh_cart01_lanterns01", 3, "Lantern"},                
    },
["coach3"] = {
    {00, 0, "No Lights"}	               
	},
["ArmySupplyWagon"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},            
 	 {"pg_veh_ArmySupplyWagon_lanterns01", 3, "Lights 1"},
	},
["bountywagon01x"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},            
 	 {"pg_teamster_chuckwagon002x_lightupgrade1", 3, "Lights 1"},
	 {"pg_teamster_chuckwagon002x_lightupgrade2", 3, "Lights 2"},
	 {"pg_teamster_chuckwagon002x_lightupgrade3", 3, "Lights 3"},
	 {"pg_veh_chuckwagon002x_lanterns01", 3, "Lantern"},
},
["buggy01"] = {
	 {00, 0, "No Lights"}
	},
["buggy02"] = {
	 {00, 0, "No Lights"}
	},
["buggy03"] = {
	 {00, 0, "No Lights"}
	},
["cart02"] = {
	 {00, 0, "No Lights"}
	},
["cart03"] = {
	 {00, 0, "No Lights"}
	},
["cart04"] = {
	 {00, 0, "No Lights"}
	},
["cart05"] = {
	 {00, 0, "No Lights"}
	},
["cart06"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},
     {"pg_re_deadbodies01x_lights", 3, "Dead Lights"},           
 	 {"pg_teamster_cart06_lightupgrade1", 3, "Lights 1"},
	 {"pg_teamster_cart06_lightupgrade2", 3, "Lights 2"},
	 {"pg_teamster_cart06_lightupgrade3", 3, "Lights 3"},
	 {"pg_veh_cart06_lanterns01", 3, "Lantern"},
	},
["cart07"] = {
	 {00, 0, "No Lights"}
	},
["cart08"] = {
	 {00, 0, "No Lights"}
	},
["chuckwagon000X"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},     
 	 {"pg_teamster_chuckwagon000x_lightupgrade1", 3, "Lights 1"},
	 {"pg_teamster_chuckwagon000x_lightupgrade2", 3, "Lights 2"},
	 {"pg_teamster_chuckwagon000x_lightupgrade3", 3, "Lights 3"},
	 {"pg_veh_chuckwagon000x_lanterns", 3, "Lantern"},
	},
["chuckwagon002X"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},     
 	 {"pg_teamster_chuckwagon002x_lightupgrade1", 3, "Lights 1"},
	 {"pg_teamster_chuckwagon002x_lightupgrade2", 3, "Lights 2"},
	 {"pg_teamster_chuckwagon002x_lightupgrade3", 3, "Lights 3"},
	 {"pg_veh_chuckwagon002x_lanterns01", 3, "Lantern"},
	},
["coach2"] = {
	 {00, 0, "No Lights"}
	},
["coach4"] = {
	 {00, 0, "No Lights"}
	},
["coach5"] = {
	 {00, 0, "No Lights"}
	},
["coach6"] = {
	 {00, 0, "No Lights"}
	},
["coal_wagon"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},     
 	 {"pg_teamster_coalwagon_lightupgrade1", 3, "Lights 1"},
	 {"pg_teamster_coalwagon_lightupgrade2", 3, "Lights 2"},
	 {"pg_teamster_coalwagon_lightupgrade3", 3, "Lights 3"},
	 {"pg_veh_coal_wagon_lanterns01", 3, "Lantern"},
	},
["gatchuck"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},     
 	 {"pg_teamster_gatchuck_lightupgrade1", 3, "Lights 1"},
	 {"pg_teamster_gatchuck_lightupgrade2", 3, "Lights 2"},
	 {"pg_teamster_gatchuck_lightupgrade3", 3, "Lights 3"},
	 {"pg_veh_gatchuck_lanterns01", 3, "Lantern"},
	},
["gatchuck_2"] = {
	 {00, 0, "No Lights"}
	},
["huntercart01"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},
     {"pg_re_deadbodies01x_lights", 3, "Dead Lights"},           
 	 {"pg_teamster_cart06_lightupgrade1", 3, "Lights 1"},
	 {"pg_teamster_cart06_lightupgrade2", 3, "Lights 2"},
	 {"pg_teamster_cart06_lightupgrade3", 3, "Lights 3"},
	 {"pg_veh_cart06_lanterns01", 3, "Lantern"},
	},
["logwagon"] = {
	 {00, 0, "No Lights"}
	},
["oilWagon01x"] = {
	 {00, 0, "No Lights"}
	},
["oilWagon02x"] = {
	 {00, 0, "No Lights"}
	},
["policeWagon01x"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},
     {"pg_veh_policeWagon01x_lanterns01", 3, "Lantern"},      
	},
["policeWagongatling01x"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},
     {"pg_veh_policeWagonGatling01x_lanterns01", 3, "Lantern"},      
	},
["stagecoach001x"] = {
	 {00, 0, "No Lights"}
	},
["stagecoach002x"] = {
	 {00, 0, "No Lights"}
	},
["stagecoach003x"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},
     {"pg_veh_stagecoach003x_lanterns01", 3, "Lantern"},      
	},
["stagecoach004_2x"] = {
	 {00, 0, "No Lights"}
	},
["stagecoach004x"] = {
	 {00, 0, "No Lights"}
	},
["stagecoach005x"] = {
	 {00, 0, "No Lights"}
	},
["stagecoach006x"] = {
	 {00, 0, "No Lights"}
	},
["supplywagon"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},
     {"pg_veh_ArmySupplyWagon_lanterns01", 3, "Lantern"},      
	},
["coal_wagon"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},     
 	 {"pg_teamster_coalwagon_lightupgrade1", 3, "Lights 1"},
	 {"pg_teamster_coalwagon_lightupgrade2", 3, "Lights 2"},
	 {"pg_teamster_coalwagon_lightupgrade3", 3, "Lights 3"},
	 {"pg_veh_coal_wagon_lanterns01", 3, "Lantern"},
	},
["wagon02x"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},     
 	 {"pg_teamster_wagon02x_lightupgrade1", 3, "Lights 1"},
	 {"pg_teamster_wagon02x_lightupgrade2", 3, "Lights 2"},
	 {"pg_teamster_wagon02x_lightupgrade3", 3, "Lights 3"},
	 {"pg_veh_wagon02x_lanterns01", 3, "Lantern"},
     {"pg_veh_wagonsuffrage_lanterns01", 3, "Lantern Suffrage"},
	},
["wagon03x"] = {
	 {00, 0, "No Lights"}
	},
["wagon04x"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},     
 	 {"pg_teamster_wagon04x_lightupgrade1", 3, "Lights 1"},
	 {"pg_teamster_wagon04x_lightupgrade2", 3, "Lights 2"},
	 {"pg_teamster_wagon04x_lightupgrade3", 3, "Lights 3"},
	 {"pg_veh_wagon04x_lanterns01", 3, "Lantern"}, 
	},
["wagon05x"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},     
 	 {"pg_teamster_wagon05x_lightupgrade1", 3, "Lights 1"},
	 {"pg_teamster_wagon05x_lightupgrade2", 3, "Lights 2"},
	 {"pg_teamster_wagon05x_lightupgrade3", 3, "Lights 3"},
	 {"pg_veh_wagon05x_2_lanterns01", 3, "Lantern"},
	 {"pg_veh_wagon05x_lanterns01", 3, "Lantern 2"}, 
	 {"pg_veh_wagon05x_lanterns02", 3, "Lantern 3"}, 
	},
["wagon06x"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},     
 	 {"pg_teamster_wagon06x_lightupgrade1", 3, "Lights 1"},
	 {"pg_teamster_wagon06x_lightupgrade2", 3, "Lights 2"},
	 {"pg_teamster_wagon06x_lightupgrade3", 3, "Lights 3"},
	},
["wagonarmoured01x"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},
     {"pg_veh_wagonarmoured01x_lanterns01", 3, "Lantern"},      
	},
["wagoncircus01x"] = {
	 {00, 0, "No Lights"}
	},
["wagonCircus02x"] = {
	 {00, 0, "No Lights"}
	},
["wagonDairy01x"] = {
	 {00, 0, "No Lights"}
	},
["WAGONDOC01X"] = {
	 {00, 0, "No Lights"}
	},
["wagonPrison01x"] = {
	 {00, 0, "Select Lights"}, 
     {false, 0, "Remove Light"},
     {"pg_veh_wagonPrison01x_lanterns01", 3, "Lantern"},      
	},
["wagontraveller01x"] = {
	 {00, 0, "No Lights"}
	},
["wagonWork01x"] = {
	 {00, 0, "No Lights"}
	},
["warWagon2"] = {
	 {00, 0, "No Lights"}
	},
},
                         
}
